/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItemId = IDL.Nat32;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MenuItemCategory = IDL.Variant({
  'dessert' : IDL.Null,
  'main' : IDL.Null,
  'appetizer' : IDL.Null,
  'beverage' : IDL.Null,
});
export const RestaurantId = IDL.Nat32;
export const AppUserRole = IDL.Variant({
  'customer' : IDL.Null,
  'restaurant_owner' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : AppUserRole,
});
export const CartItemId = IDL.Nat32;
export const CartItem = IDL.Record({
  'id' : CartItemId,
  'userId' : IDL.Principal,
  'quantity' : IDL.Nat,
  'menuItemId' : MenuItemId,
});
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'restaurantId' : RestaurantId,
  'imageUrl' : IDL.Text,
  'category' : MenuItemCategory,
  'price' : IDL.Float64,
});
export const OrderId = IDL.Nat32;
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'ready' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
  'menuItemId' : MenuItemId,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'total' : IDL.Float64,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'items' : IDL.Vec(OrderItem),
});
export const Restaurant = IDL.Record({
  'id' : RestaurantId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'cuisineType' : IDL.Text,
  'description' : IDL.Text,
  'deliveryTimeEstimate' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'rating' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([MenuItemId, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMenuItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        MenuItemCategory,
        IDL.Text,
        RestaurantId,
      ],
      [MenuItemId],
      [],
    ),
  'createRestaurant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text],
      [RestaurantId],
      [],
    ),
  'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Float64,
          'items' : IDL.Vec(IDL.Tuple(CartItem, MenuItem)),
        }),
      ],
      ['query'],
    ),
  'getMenuItem' : IDL.Func([MenuItemId], [IDL.Opt(MenuItem)], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getRestaurant' : IDL.Func([RestaurantId], [IDL.Opt(Restaurant)], ['query']),
  'getRestaurantOrders' : IDL.Func([RestaurantId], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMenuItems' : IDL.Func([RestaurantId], [IDL.Vec(MenuItem)], ['query']),
  'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'placeOrder' : IDL.Func([IDL.Text], [OrderId], []),
  'registerUser' : IDL.Func([IDL.Text, AppUserRole], [], []),
  'removeFromCart' : IDL.Func([CartItemId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchRestaurants' : IDL.Func([IDL.Text], [IDL.Vec(Restaurant)], ['query']),
  'updateCartItemQuantity' : IDL.Func([CartItemId, IDL.Nat], [], []),
  'updateMenuItem' : IDL.Func(
      [
        MenuItemId,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        MenuItemCategory,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateRestaurant' : IDL.Func(
      [
        RestaurantId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItemId = IDL.Nat32;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MenuItemCategory = IDL.Variant({
    'dessert' : IDL.Null,
    'main' : IDL.Null,
    'appetizer' : IDL.Null,
    'beverage' : IDL.Null,
  });
  const RestaurantId = IDL.Nat32;
  const AppUserRole = IDL.Variant({
    'customer' : IDL.Null,
    'restaurant_owner' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : AppUserRole });
  const CartItemId = IDL.Nat32;
  const CartItem = IDL.Record({
    'id' : CartItemId,
    'userId' : IDL.Principal,
    'quantity' : IDL.Nat,
    'menuItemId' : MenuItemId,
  });
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'restaurantId' : RestaurantId,
    'imageUrl' : IDL.Text,
    'category' : MenuItemCategory,
    'price' : IDL.Float64,
  });
  const OrderId = IDL.Nat32;
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'ready' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
    'menuItemId' : MenuItemId,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'total' : IDL.Float64,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'updatedAt' : Time,
    'items' : IDL.Vec(OrderItem),
  });
  const Restaurant = IDL.Record({
    'id' : RestaurantId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'cuisineType' : IDL.Text,
    'description' : IDL.Text,
    'deliveryTimeEstimate' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'rating' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([MenuItemId, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMenuItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          MenuItemCategory,
          IDL.Text,
          RestaurantId,
        ],
        [MenuItemId],
        [],
      ),
    'createRestaurant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text],
        [RestaurantId],
        [],
      ),
    'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Float64,
            'items' : IDL.Vec(IDL.Tuple(CartItem, MenuItem)),
          }),
        ],
        ['query'],
      ),
    'getMenuItem' : IDL.Func([MenuItemId], [IDL.Opt(MenuItem)], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Opt(Restaurant)],
        ['query'],
      ),
    'getRestaurantOrders' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMenuItems' : IDL.Func([RestaurantId], [IDL.Vec(MenuItem)], ['query']),
    'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'placeOrder' : IDL.Func([IDL.Text], [OrderId], []),
    'registerUser' : IDL.Func([IDL.Text, AppUserRole], [], []),
    'removeFromCart' : IDL.Func([CartItemId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchRestaurants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'updateCartItemQuantity' : IDL.Func([CartItemId, IDL.Nat], [], []),
    'updateMenuItem' : IDL.Func(
        [
          MenuItemId,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          MenuItemCategory,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateRestaurant' : IDL.Func(
        [
          RestaurantId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };