/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'customer' : null } |
  { 'restaurant_owner' : null };
export interface CartItem {
  'id' : CartItemId,
  'userId' : Principal,
  'quantity' : bigint,
  'menuItemId' : MenuItemId,
}
export type CartItemId = number;
export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'restaurantId' : RestaurantId,
  'imageUrl' : string,
  'category' : MenuItemCategory,
  'price' : number,
}
export type MenuItemCategory = { 'dessert' : null } |
  { 'main' : null } |
  { 'appetizer' : null } |
  { 'beverage' : null };
export type MenuItemId = number;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'total' : number,
  'userId' : Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'items' : Array<OrderItem>,
}
export type OrderId = number;
export interface OrderItem {
  'quantity' : bigint,
  'price' : number,
  'menuItemId' : MenuItemId,
}
export type OrderStatus = { 'preparing' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'ready' : null };
export interface Restaurant {
  'id' : RestaurantId,
  'owner' : Principal,
  'name' : string,
  'cuisineType' : string,
  'description' : string,
  'deliveryTimeEstimate' : bigint,
  'imageUrl' : string,
  'rating' : number,
}
export type RestaurantId = number;
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : AppUserRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[MenuItemId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMenuItem' : ActorMethod<
    [string, string, number, MenuItemCategory, string, RestaurantId],
    MenuItemId
  >,
  'createRestaurant' : ActorMethod<
    [string, string, string, number, bigint, string],
    RestaurantId
  >,
  'deleteMenuItem' : ActorMethod<[MenuItemId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<
    [],
    { 'total' : number, 'items' : Array<[CartItem, MenuItem]> }
  >,
  'getMenuItem' : ActorMethod<[MenuItemId], [] | [MenuItem]>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getRestaurant' : ActorMethod<[RestaurantId], [] | [Restaurant]>,
  'getRestaurantOrders' : ActorMethod<[RestaurantId], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMenuItems' : ActorMethod<[RestaurantId], Array<MenuItem>>,
  'listRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'placeOrder' : ActorMethod<[string], OrderId>,
  'registerUser' : ActorMethod<[string, AppUserRole], undefined>,
  'removeFromCart' : ActorMethod<[CartItemId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchRestaurants' : ActorMethod<[string], Array<Restaurant>>,
  'updateCartItemQuantity' : ActorMethod<[CartItemId, bigint], undefined>,
  'updateMenuItem' : ActorMethod<
    [MenuItemId, string, string, number, MenuItemCategory, string, boolean],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateRestaurant' : ActorMethod<
    [RestaurantId, string, string, string, number, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];